// Search/Autocomplete - https://api.weatherapi.com/v1/search.json?key=76885444e1af40a483b134610240305&q=London -
export const autocompleteApiData = [
    {
        "id": 2801268,
        "name": "London",
        "region": "City of London, Greater London",
        "country": "United Kingdom",
        "lat": 51.52,
        "lon": -0.11,
        "url": "london-city-of-london-greater-london-united-kingdom"
    },
    {
        "id": 315398,
        "name": "London",
        "region": "Ontario",
        "country": "Canada",
        "lat": 42.98,
        "lon": -81.25,
        "url": "london-ontario-canada"
    }
]

// Forecast - https://api.weatherapi.com/v1/forecast.json?key=76885444e1af40a483b134610240305&q=London&days=1&aqi=no&alerts=no -
export const forecastApiData = {
    "location": {
        "name": "London",
        "region": "City of London, Greater London",
        "country": "United Kingdom",
        "lat": 51.52,
        "lon": -0.11,
        "tz_id": "Europe/London",
        "localtime_epoch": 1714745157,
        "localtime": "2024-05-03 15:05"
    },
    "current": {
        "last_updated_epoch": 1714744800,
        "last_updated": "2024-05-03 15:00",
        "temp_c": 11.0,
        "temp_f": 51.8,
        "is_day": 1,
        "condition": {
            "text": "Light rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
            "code": 1183
        },
        "wind_mph": 16.1,
        "wind_kph": 25.9,
        "wind_degree": 250,
        "wind_dir": "WSW",
        "pressure_mb": 1010.0,
        "pressure_in": 29.83,
        "precip_mm": 0.35,
        "precip_in": 0.01,
        "humidity": 82,
        "cloud": 0,
        "feelslike_c": 9.2,
        "feelslike_f": 48.5,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 2.0,
        "gust_mph": 20.6,
        "gust_kph": 33.1
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2024-05-03",
                "date_epoch": 1714694400,
                "day": {
                    "maxtemp_c": 10.2,
                    "maxtemp_f": 50.3,
                    "mintemp_c": 7.9,
                    "mintemp_f": 46.2,
                    "avgtemp_c": 9.3,
                    "avgtemp_f": 48.7,
                    "maxwind_mph": 13.0,
                    "maxwind_kph": 20.9,
                    "totalprecip_mm": 6.54,
                    "totalprecip_in": 0.26,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 6.8,
                    "avgvis_miles": 4.0,
                    "avghumidity": 92,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 96,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Moderate rain",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                        "code": 1189
                    },
                    "uv": 1.0
                },
                "astro": {
                    "sunrise": "05:28 AM",
                    "sunset": "08:28 PM",
                    "moonrise": "03:54 AM",
                    "moonset": "02:13 PM",
                    "moon_phase": "Waning Crescent",
                    "moon_illumination": 33,
                    "is_moon_up": 0,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1714690800,
                        "time": "2024-05-03 00:00",
                        "temp_c": 10.2,
                        "temp_f": 50.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 256,
                        "wind_dir": "WSW",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.69,
                        "precip_mm": 0.02,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 8.1,
                        "feelslike_f": 46.6,
                        "windchill_c": 8.1,
                        "windchill_f": 46.6,
                        "heatindex_c": 10.2,
                        "heatindex_f": 50.4,
                        "dewpoint_c": 8.6,
                        "dewpoint_f": 47.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 81,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.4,
                        "gust_kph": 21.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714694400,
                        "time": "2024-05-03 01:00",
                        "temp_c": 9.9,
                        "temp_f": 49.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 253,
                        "wind_dir": "WSW",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.06,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 7.8,
                        "feelslike_f": 46.0,
                        "windchill_c": 7.8,
                        "windchill_f": 46.0,
                        "heatindex_c": 10.0,
                        "heatindex_f": 49.9,
                        "dewpoint_c": 8.2,
                        "dewpoint_f": 46.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.5,
                        "gust_kph": 21.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714698000,
                        "time": "2024-05-03 02:00",
                        "temp_c": 9.7,
                        "temp_f": 49.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 256,
                        "wind_dir": "WSW",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.02,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 7.3,
                        "feelslike_f": 45.2,
                        "windchill_c": 7.3,
                        "windchill_f": 45.2,
                        "heatindex_c": 9.7,
                        "heatindex_f": 49.4,
                        "dewpoint_c": 7.9,
                        "dewpoint_f": 46.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 71,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 14.5,
                        "gust_kph": 23.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714701600,
                        "time": "2024-05-03 03:00",
                        "temp_c": 9.5,
                        "temp_f": 49.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 10.7,
                        "wind_kph": 17.3,
                        "wind_degree": 254,
                        "wind_dir": "WSW",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.04,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 7.0,
                        "feelslike_f": 44.7,
                        "windchill_c": 7.0,
                        "windchill_f": 44.7,
                        "heatindex_c": 9.5,
                        "heatindex_f": 49.1,
                        "dewpoint_c": 7.9,
                        "dewpoint_f": 46.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 65,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.4,
                        "gust_kph": 24.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714705200,
                        "time": "2024-05-03 04:00",
                        "temp_c": 9.4,
                        "temp_f": 48.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 11.0,
                        "wind_kph": 17.6,
                        "wind_degree": 253,
                        "wind_dir": "WSW",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.02,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 6.9,
                        "feelslike_f": 44.4,
                        "windchill_c": 6.9,
                        "windchill_f": 44.4,
                        "heatindex_c": 9.4,
                        "heatindex_f": 48.9,
                        "dewpoint_c": 7.7,
                        "dewpoint_f": 45.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 84,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.8,
                        "gust_kph": 25.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714708800,
                        "time": "2024-05-03 05:00",
                        "temp_c": 9.5,
                        "temp_f": 49.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                            "code": 1009
                        },
                        "wind_mph": 11.2,
                        "wind_kph": 18.0,
                        "wind_degree": 252,
                        "wind_dir": "WSW",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.71,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 88,
                        "cloud": 100,
                        "feelslike_c": 6.9,
                        "feelslike_f": 44.5,
                        "windchill_c": 6.9,
                        "windchill_f": 44.5,
                        "heatindex_c": 9.5,
                        "heatindex_f": 49.1,
                        "dewpoint_c": 7.5,
                        "dewpoint_f": 45.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.0,
                        "gust_kph": 25.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714712400,
                        "time": "2024-05-03 06:00",
                        "temp_c": 9.6,
                        "temp_f": 49.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 11.0,
                        "wind_kph": 17.6,
                        "wind_degree": 250,
                        "wind_dir": "WSW",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.73,
                        "precip_mm": 0.03,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 87,
                        "cloud": 100,
                        "feelslike_c": 7.1,
                        "feelslike_f": 44.8,
                        "windchill_c": 7.1,
                        "windchill_f": 44.8,
                        "heatindex_c": 9.6,
                        "heatindex_f": 49.3,
                        "dewpoint_c": 7.5,
                        "dewpoint_f": 45.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 60,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.2,
                        "gust_kph": 24.5,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714716000,
                        "time": "2024-05-03 07:00",
                        "temp_c": 9.4,
                        "temp_f": 49.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 11.4,
                        "wind_kph": 18.4,
                        "wind_degree": 246,
                        "wind_dir": "WSW",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.74,
                        "precip_mm": 0.07,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 88,
                        "cloud": 100,
                        "feelslike_c": 6.8,
                        "feelslike_f": 44.3,
                        "windchill_c": 6.8,
                        "windchill_f": 44.3,
                        "heatindex_c": 9.4,
                        "heatindex_f": 49.0,
                        "dewpoint_c": 7.6,
                        "dewpoint_f": 45.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.8,
                        "gust_kph": 25.4,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714719600,
                        "time": "2024-05-03 08:00",
                        "temp_c": 9.2,
                        "temp_f": 48.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 11.6,
                        "wind_kph": 18.7,
                        "wind_degree": 244,
                        "wind_dir": "WSW",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.75,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 91,
                        "cloud": 100,
                        "feelslike_c": 6.5,
                        "feelslike_f": 43.7,
                        "windchill_c": 6.5,
                        "windchill_f": 43.7,
                        "heatindex_c": 9.2,
                        "heatindex_f": 48.6,
                        "dewpoint_c": 7.9,
                        "dewpoint_f": 46.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 16.2,
                        "gust_kph": 26.1,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714723200,
                        "time": "2024-05-03 09:00",
                        "temp_c": 9.0,
                        "temp_f": 48.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 12.5,
                        "wind_kph": 20.2,
                        "wind_degree": 246,
                        "wind_dir": "WSW",
                        "pressure_mb": 1008.0,
                        "pressure_in": 29.76,
                        "precip_mm": 0.39,
                        "precip_in": 0.02,
                        "snow_cm": 0.0,
                        "humidity": 93,
                        "cloud": 100,
                        "feelslike_c": 6.1,
                        "feelslike_f": 43.1,
                        "windchill_c": 6.1,
                        "windchill_f": 43.1,
                        "heatindex_c": 9.0,
                        "heatindex_f": 48.3,
                        "dewpoint_c": 8.0,
                        "dewpoint_f": 46.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 17.8,
                        "gust_kph": 28.6,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714726800,
                        "time": "2024-05-03 10:00",
                        "temp_c": 8.9,
                        "temp_f": 48.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 13.0,
                        "wind_kph": 20.9,
                        "wind_degree": 242,
                        "wind_dir": "WSW",
                        "pressure_mb": 1008.0,
                        "pressure_in": 29.77,
                        "precip_mm": 0.71,
                        "precip_in": 0.03,
                        "snow_cm": 0.0,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 5.9,
                        "feelslike_f": 42.6,
                        "windchill_c": 5.9,
                        "windchill_f": 42.6,
                        "heatindex_c": 8.9,
                        "heatindex_f": 48.0,
                        "dewpoint_c": 8.1,
                        "dewpoint_f": 46.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 18.5,
                        "gust_kph": 29.8,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714730400,
                        "time": "2024-05-03 11:00",
                        "temp_c": 8.8,
                        "temp_f": 47.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 12.1,
                        "wind_kph": 19.4,
                        "wind_degree": 243,
                        "wind_dir": "WSW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.79,
                        "precip_mm": 0.95,
                        "precip_in": 0.04,
                        "snow_cm": 0.0,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 6.0,
                        "feelslike_f": 42.7,
                        "windchill_c": 6.0,
                        "windchill_f": 42.7,
                        "heatindex_c": 8.8,
                        "heatindex_f": 47.9,
                        "dewpoint_c": 8.0,
                        "dewpoint_f": 46.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 17.4,
                        "gust_kph": 28.1,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714734000,
                        "time": "2024-05-03 12:00",
                        "temp_c": 8.7,
                        "temp_f": 47.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 10.7,
                        "wind_kph": 17.3,
                        "wind_degree": 241,
                        "wind_dir": "WSW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.81,
                        "precip_mm": 1.21,
                        "precip_in": 0.05,
                        "snow_cm": 0.0,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 6.1,
                        "feelslike_f": 43.0,
                        "windchill_c": 6.1,
                        "windchill_f": 43.0,
                        "heatindex_c": 8.8,
                        "heatindex_f": 47.8,
                        "dewpoint_c": 8.0,
                        "dewpoint_f": 46.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 15.8,
                        "gust_kph": 25.4,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714737600,
                        "time": "2024-05-03 13:00",
                        "temp_c": 8.9,
                        "temp_f": 47.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 11.4,
                        "wind_kph": 18.4,
                        "wind_degree": 238,
                        "wind_dir": "WSW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.82,
                        "precip_mm": 1.46,
                        "precip_in": 0.06,
                        "snow_cm": 0.0,
                        "humidity": 94,
                        "cloud": 100,
                        "feelslike_c": 6.1,
                        "feelslike_f": 43.0,
                        "windchill_c": 6.1,
                        "windchill_f": 43.0,
                        "heatindex_c": 8.9,
                        "heatindex_f": 47.9,
                        "dewpoint_c": 8.0,
                        "dewpoint_f": 46.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 16.7,
                        "gust_kph": 26.8,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714741200,
                        "time": "2024-05-03 14:00",
                        "temp_c": 9.1,
                        "temp_f": 48.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 11.0,
                        "wind_kph": 17.6,
                        "wind_degree": 247,
                        "wind_dir": "WSW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.82,
                        "precip_mm": 0.79,
                        "precip_in": 0.03,
                        "snow_cm": 0.0,
                        "humidity": 93,
                        "cloud": 100,
                        "feelslike_c": 6.5,
                        "feelslike_f": 43.8,
                        "windchill_c": 6.5,
                        "windchill_f": 43.8,
                        "heatindex_c": 9.1,
                        "heatindex_f": 48.4,
                        "dewpoint_c": 8.1,
                        "dewpoint_f": 46.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 16.0,
                        "gust_kph": 25.8,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714744800,
                        "time": "2024-05-03 15:00",
                        "temp_c": 11.0,
                        "temp_f": 51.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 16.1,
                        "wind_kph": 25.9,
                        "wind_degree": 250,
                        "wind_dir": "WSW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.83,
                        "precip_mm": 0.35,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 82,
                        "cloud": 0,
                        "feelslike_c": 7.4,
                        "feelslike_f": 45.4,
                        "windchill_c": 7.4,
                        "windchill_f": 45.4,
                        "heatindex_c": 9.6,
                        "heatindex_f": 49.2,
                        "dewpoint_c": 8.1,
                        "dewpoint_f": 46.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.6,
                        "gust_kph": 33.1,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714748400,
                        "time": "2024-05-03 16:00",
                        "temp_c": 9.9,
                        "temp_f": 49.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 7.2,
                        "wind_kph": 11.5,
                        "wind_degree": 255,
                        "wind_dir": "WSW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.84,
                        "precip_mm": 0.18,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 8.3,
                        "feelslike_f": 46.9,
                        "windchill_c": 8.3,
                        "windchill_f": 46.9,
                        "heatindex_c": 9.9,
                        "heatindex_f": 49.9,
                        "dewpoint_c": 8.3,
                        "dewpoint_f": 46.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 10.4,
                        "gust_kph": 16.8,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714752000,
                        "time": "2024-05-03 17:00",
                        "temp_c": 10.2,
                        "temp_f": 50.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 252,
                        "wind_dir": "WSW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.84,
                        "precip_mm": 0.03,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 69,
                        "feelslike_c": 9.0,
                        "feelslike_f": 48.2,
                        "windchill_c": 9.0,
                        "windchill_f": 48.2,
                        "heatindex_c": 10.2,
                        "heatindex_f": 50.3,
                        "dewpoint_c": 8.5,
                        "dewpoint_f": 47.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 60,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.2,
                        "gust_kph": 13.2,
                        "uv": 3.0
                    },
                    {
                        "time_epoch": 1714755600,
                        "time": "2024-05-03 18:00",
                        "temp_c": 10.0,
                        "temp_f": 50.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 240,
                        "wind_dir": "WSW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.83,
                        "precip_mm": 0.01,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 91,
                        "cloud": 70,
                        "feelslike_c": 9.0,
                        "feelslike_f": 48.2,
                        "windchill_c": 9.0,
                        "windchill_f": 48.2,
                        "heatindex_c": 10.0,
                        "heatindex_f": 50.0,
                        "dewpoint_c": 8.5,
                        "dewpoint_f": 47.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 83,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.7,
                        "gust_kph": 12.4,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714759200,
                        "time": "2024-05-03 19:00",
                        "temp_c": 9.5,
                        "temp_f": 49.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 4.0,
                        "wind_kph": 6.5,
                        "wind_degree": 215,
                        "wind_dir": "SW",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.85,
                        "precip_mm": 0.01,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 93,
                        "cloud": 90,
                        "feelslike_c": 8.7,
                        "feelslike_f": 47.7,
                        "windchill_c": 8.7,
                        "windchill_f": 47.7,
                        "heatindex_c": 9.5,
                        "heatindex_f": 49.0,
                        "dewpoint_c": 8.3,
                        "dewpoint_f": 47.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 75,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.0,
                        "gust_kph": 11.3,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714762800,
                        "time": "2024-05-03 20:00",
                        "temp_c": 8.9,
                        "temp_f": 48.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                            "code": 1030
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 207,
                        "wind_dir": "SSW",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.86,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 94,
                        "cloud": 88,
                        "feelslike_c": 7.8,
                        "feelslike_f": 46.0,
                        "windchill_c": 7.8,
                        "windchill_f": 46.0,
                        "heatindex_c": 8.9,
                        "heatindex_f": 48.0,
                        "dewpoint_c": 8.1,
                        "dewpoint_f": 46.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 8.8,
                        "gust_kph": 14.1,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1714766400,
                        "time": "2024-05-03 21:00",
                        "temp_c": 8.5,
                        "temp_f": 47.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                            "code": 1030
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 205,
                        "wind_dir": "SSW",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 96,
                        "cloud": 70,
                        "feelslike_c": 7.3,
                        "feelslike_f": 45.1,
                        "windchill_c": 7.3,
                        "windchill_f": 45.1,
                        "heatindex_c": 8.5,
                        "heatindex_f": 47.3,
                        "dewpoint_c": 7.9,
                        "dewpoint_f": 46.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 9.3,
                        "gust_kph": 14.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714770000,
                        "time": "2024-05-03 22:00",
                        "temp_c": 8.2,
                        "temp_f": 46.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                            "code": 1030
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 207,
                        "wind_dir": "SSW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 97,
                        "cloud": 43,
                        "feelslike_c": 6.8,
                        "feelslike_f": 44.2,
                        "windchill_c": 6.8,
                        "windchill_f": 44.2,
                        "heatindex_c": 8.2,
                        "heatindex_f": 46.7,
                        "dewpoint_c": 7.6,
                        "dewpoint_f": 45.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714773600,
                        "time": "2024-05-03 23:00",
                        "temp_c": 7.9,
                        "temp_f": 46.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                            "code": 1030
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 202,
                        "wind_dir": "SSW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 96,
                        "cloud": 34,
                        "feelslike_c": 6.4,
                        "feelslike_f": 43.5,
                        "windchill_c": 6.4,
                        "windchill_f": 43.5,
                        "heatindex_c": 7.9,
                        "heatindex_f": 46.2,
                        "dewpoint_c": 7.4,
                        "dewpoint_f": 45.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 9.7,
                        "gust_kph": 15.6,
                        "uv": 1.0
                    }
                ]
            }
        ]
    }
}

// Current - https://api.weatherapi.com/v1/current.json?key=76885444e1af40a483b134610240305&q=London&aqi=no
export const currentWeatherApiData = {
    "location": {
        "name": "London",
        "region": "City of London, Greater London",
        "country": "United Kingdom",
        "lat": 51.52,
        "lon": -0.11,
        "tz_id": "Europe/London",
        "localtime_epoch": 1714745556,
        "localtime": "2024-05-03 15:12"
    },
    "current": {
        "last_updated_epoch": 1714744800,
        "last_updated": "2024-05-03 15:00",
        "temp_c": 11.0,
        "temp_f": 51.8,
        "is_day": 1,
        "condition": {
            "text": "Light rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
            "code": 1183
        },
        "wind_mph": 16.1,
        "wind_kph": 25.9,
        "wind_degree": 250,
        "wind_dir": "WSW",
        "pressure_mb": 1010.0,
        "pressure_in": 29.83,
        "precip_mm": 0.35,
        "precip_in": 0.01,
        "humidity": 82,
        "cloud": 0,
        "feelslike_c": 9.2,
        "feelslike_f": 48.5,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 2.0,
        "gust_mph": 20.6,
        "gust_kph": 33.1
    }
}
